spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/travellab?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Europe/Kiev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

travellab:
  oauth:
    client-id: "travellab_id"
    client-secret: "travellab_secret"

server:
  address: localhost
  port: 8080
